// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * ChangedFile represents a file changed in a PR
 */
export class ChangedFile {
    "Path": string;
    "Status": FileStatus;
    "Additions": number;
    "Deletions": number;
    "Patch": string;

    /**
     * For renames
     */
    "PrevPath": string;

    /** Creates a new ChangedFile instance. */
    constructor($$source: Partial<ChangedFile> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Status" in $$source)) {
            this["Status"] = FileStatus.$zero;
        }
        if (!("Additions" in $$source)) {
            this["Additions"] = 0;
        }
        if (!("Deletions" in $$source)) {
            this["Deletions"] = 0;
        }
        if (!("Patch" in $$source)) {
            this["Patch"] = "";
        }
        if (!("PrevPath" in $$source)) {
            this["PrevPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChangedFile instance from a string or object.
     */
    static createFrom($$source: any = {}): ChangedFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChangedFile($$parsedSource as Partial<ChangedFile>);
    }
}

/**
 * Check represents a CI check/status
 */
export class Check {
    "Name": string;
    "Status": CheckStatus;
    "Conclusion": CheckConclusion;
    "URL": string;
    "StartedAt": time$0.Time;
    "CompletedAt": time$0.Time;

    /** Creates a new Check instance. */
    constructor($$source: Partial<Check> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Status" in $$source)) {
            this["Status"] = CheckStatus.$zero;
        }
        if (!("Conclusion" in $$source)) {
            this["Conclusion"] = CheckConclusion.$zero;
        }
        if (!("URL" in $$source)) {
            this["URL"] = "";
        }
        if (!("StartedAt" in $$source)) {
            this["StartedAt"] = null;
        }
        if (!("CompletedAt" in $$source)) {
            this["CompletedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Check instance from a string or object.
     */
    static createFrom($$source: any = {}): Check {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Check($$parsedSource as Partial<Check>);
    }
}

/**
 * CheckConclusion represents the conclusion of a completed check
 */
export enum CheckConclusion {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CheckSuccess = "success",
    CheckFailure = "failure",
    CheckNeutral = "neutral",
    CheckCancelled = "cancelled",
    CheckTimedOut = "timed_out",
    CheckSkipped = "skipped",
};

/**
 * CheckStatus represents the status of a check
 */
export enum CheckStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CheckQueued = "queued",
    CheckInProgress = "in_progress",
    CheckCompleted = "completed",
};

/**
 * Comment represents a comment on a PR
 */
export class Comment {
    "ID": number;
    "Author": User;
    "Body": string;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;
    "Resolved": boolean;

    /**
     * For inline comments
     */
    "Path": string;
    "Line": number;
    "OrigLine": number;
    "Side": DiffSide;
    "InReplyTo": number | null;
    "DiffHunk": string;
    "CommitID": string;

    /** Creates a new Comment instance. */
    constructor($$source: Partial<Comment> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Author" in $$source)) {
            this["Author"] = (new User());
        }
        if (!("Body" in $$source)) {
            this["Body"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }
        if (!("Resolved" in $$source)) {
            this["Resolved"] = false;
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Line" in $$source)) {
            this["Line"] = 0;
        }
        if (!("OrigLine" in $$source)) {
            this["OrigLine"] = 0;
        }
        if (!("Side" in $$source)) {
            this["Side"] = DiffSide.$zero;
        }
        if (!("InReplyTo" in $$source)) {
            this["InReplyTo"] = null;
        }
        if (!("DiffHunk" in $$source)) {
            this["DiffHunk"] = "";
        }
        if (!("CommitID" in $$source)) {
            this["CommitID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Comment instance from a string or object.
     */
    static createFrom($$source: any = {}): Comment {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Author" in $$parsedSource) {
            $$parsedSource["Author"] = $$createField1_0($$parsedSource["Author"]);
        }
        return new Comment($$parsedSource as Partial<Comment>);
    }
}

/**
 * DiffSide indicates which side of the diff
 */
export enum DiffSide {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SideLeft = "LEFT",
    SideRight = "RIGHT",
};

/**
 * FileStatus represents the status of a changed file
 */
export enum FileStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FileAdded = "added",
    FileModified = "modified",
    FileDeleted = "deleted",
    FileRenamed = "renamed",
    FileCopied = "copied",
};

/**
 * InlineCommentInput for adding an inline comment on a diff
 */
export class InlineCommentInput {
    "Path": string;
    "Line": number;
    "Side": DiffSide;
    "Body": string;
    "InReplyTo": number | null;

    /** Creates a new InlineCommentInput instance. */
    constructor($$source: Partial<InlineCommentInput> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Line" in $$source)) {
            this["Line"] = 0;
        }
        if (!("Side" in $$source)) {
            this["Side"] = DiffSide.$zero;
        }
        if (!("Body" in $$source)) {
            this["Body"] = "";
        }
        if (!("InReplyTo" in $$source)) {
            this["InReplyTo"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InlineCommentInput instance from a string or object.
     */
    static createFrom($$source: any = {}): InlineCommentInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InlineCommentInput($$parsedSource as Partial<InlineCommentInput>);
    }
}

/**
 * ListPRsOpts configures PR listing
 */
export class ListPRsOpts {
    /**
     * Filter by state (empty = all open)
     */
    "State": PRState;

    /**
     * Filter by author
     */
    "Author": string;

    /**
     * Max results (0 = default)
     */
    "Limit": number;

    /** Creates a new ListPRsOpts instance. */
    constructor($$source: Partial<ListPRsOpts> = {}) {
        if (!("State" in $$source)) {
            this["State"] = PRState.$zero;
        }
        if (!("Author" in $$source)) {
            this["Author"] = "";
        }
        if (!("Limit" in $$source)) {
            this["Limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListPRsOpts instance from a string or object.
     */
    static createFrom($$source: any = {}): ListPRsOpts {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListPRsOpts($$parsedSource as Partial<ListPRsOpts>);
    }
}

/**
 * MergeMethod defines how to merge
 */
export enum MergeMethod {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MergeMerge = "merge",
    MergeSquash = "squash",
    MergeRebase = "rebase",
};

/**
 * MergeOpts configures merge behavior
 */
export class MergeOpts {
    /**
     * merge, squash, rebase
     */
    "Method": MergeMethod;
    "CommitTitle": string;
    "CommitMessage": string;
    "DeleteBranch": boolean;

    /** Creates a new MergeOpts instance. */
    constructor($$source: Partial<MergeOpts> = {}) {
        if (!("Method" in $$source)) {
            this["Method"] = MergeMethod.$zero;
        }
        if (!("CommitTitle" in $$source)) {
            this["CommitTitle"] = "";
        }
        if (!("CommitMessage" in $$source)) {
            this["CommitMessage"] = "";
        }
        if (!("DeleteBranch" in $$source)) {
            this["DeleteBranch"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeOpts instance from a string or object.
     */
    static createFrom($$source: any = {}): MergeOpts {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MergeOpts($$parsedSource as Partial<MergeOpts>);
    }
}

/**
 * PRState represents the state of a PR
 */
export enum PRState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PROpen = "open",
    PRClosed = "closed",
    PRMerged = "merged",
    PRAll = "all",
};

/**
 * PullRequest represents a PR/MR
 */
export class PullRequest {
    "ID": number;
    "Number": number;
    "Title": string;
    "Body": string;
    "State": PRState;
    "Author": User;
    "BaseBranch": string;
    "HeadBranch": string;
    "HeadSHA": string;
    "Draft": boolean;
    "Mergeable": boolean | null;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;
    "Labels": string[];
    "Reviewers": User[];
    "Checks": Check[];
    "URL": string;
    "Additions": number;
    "Deletions": number;
    "ChangedFiles": number;

    /** Creates a new PullRequest instance. */
    constructor($$source: Partial<PullRequest> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Number" in $$source)) {
            this["Number"] = 0;
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Body" in $$source)) {
            this["Body"] = "";
        }
        if (!("State" in $$source)) {
            this["State"] = PRState.$zero;
        }
        if (!("Author" in $$source)) {
            this["Author"] = (new User());
        }
        if (!("BaseBranch" in $$source)) {
            this["BaseBranch"] = "";
        }
        if (!("HeadBranch" in $$source)) {
            this["HeadBranch"] = "";
        }
        if (!("HeadSHA" in $$source)) {
            this["HeadSHA"] = "";
        }
        if (!("Draft" in $$source)) {
            this["Draft"] = false;
        }
        if (!("Mergeable" in $$source)) {
            this["Mergeable"] = null;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }
        if (!("Labels" in $$source)) {
            this["Labels"] = [];
        }
        if (!("Reviewers" in $$source)) {
            this["Reviewers"] = [];
        }
        if (!("Checks" in $$source)) {
            this["Checks"] = [];
        }
        if (!("URL" in $$source)) {
            this["URL"] = "";
        }
        if (!("Additions" in $$source)) {
            this["Additions"] = 0;
        }
        if (!("Deletions" in $$source)) {
            this["Deletions"] = 0;
        }
        if (!("ChangedFiles" in $$source)) {
            this["ChangedFiles"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PullRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PullRequest {
        const $$createField5_0 = $$createType0;
        const $$createField13_0 = $$createType1;
        const $$createField14_0 = $$createType2;
        const $$createField15_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Author" in $$parsedSource) {
            $$parsedSource["Author"] = $$createField5_0($$parsedSource["Author"]);
        }
        if ("Labels" in $$parsedSource) {
            $$parsedSource["Labels"] = $$createField13_0($$parsedSource["Labels"]);
        }
        if ("Reviewers" in $$parsedSource) {
            $$parsedSource["Reviewers"] = $$createField14_0($$parsedSource["Reviewers"]);
        }
        if ("Checks" in $$parsedSource) {
            $$parsedSource["Checks"] = $$createField15_0($$parsedSource["Checks"]);
        }
        return new PullRequest($$parsedSource as Partial<PullRequest>);
    }
}

/**
 * Review represents a review on a PR
 */
export class Review {
    "ID": number;
    "Author": User;
    "State": ReviewState;
    "Body": string;
    "CreatedAt": time$0.Time;

    /** Creates a new Review instance. */
    constructor($$source: Partial<Review> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Author" in $$source)) {
            this["Author"] = (new User());
        }
        if (!("State" in $$source)) {
            this["State"] = ReviewState.$zero;
        }
        if (!("Body" in $$source)) {
            this["Body"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Review instance from a string or object.
     */
    static createFrom($$source: any = {}): Review {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Author" in $$parsedSource) {
            $$parsedSource["Author"] = $$createField1_0($$parsedSource["Author"]);
        }
        return new Review($$parsedSource as Partial<Review>);
    }
}

/**
 * ReviewState represents the state of a review
 */
export enum ReviewState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ReviewApproved = "APPROVED",
    ReviewChangesRequested = "CHANGES_REQUESTED",
    ReviewCommented = "COMMENTED",
    ReviewPending = "PENDING",
    ReviewDismissed = "DISMISSED",
};

/**
 * SubmitReviewInput for submitting a review
 */
export class SubmitReviewInput {
    "State": ReviewState;
    "Body": string;

    /**
     * Pending inline comments
     */
    "Comments": InlineCommentInput[];

    /** Creates a new SubmitReviewInput instance. */
    constructor($$source: Partial<SubmitReviewInput> = {}) {
        if (!("State" in $$source)) {
            this["State"] = ReviewState.$zero;
        }
        if (!("Body" in $$source)) {
            this["Body"] = "";
        }
        if (!("Comments" in $$source)) {
            this["Comments"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubmitReviewInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SubmitReviewInput {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Comments" in $$parsedSource) {
            $$parsedSource["Comments"] = $$createField2_0($$parsedSource["Comments"]);
        }
        return new SubmitReviewInput($$parsedSource as Partial<SubmitReviewInput>);
    }
}

/**
 * User represents a user
 */
export class User {
    "ID": number;
    "Login": string;
    "Name": string;
    "Email": string;
    "AvatarURL": string;

    /** Creates a new User instance. */
    constructor($$source: Partial<User> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Login" in $$source)) {
            this["Login"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Email" in $$source)) {
            this["Email"] = "";
        }
        if (!("AvatarURL" in $$source)) {
            this["AvatarURL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     */
    static createFrom($$source: any = {}): User {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User($$parsedSource as Partial<User>);
    }
}

// Private type creation functions
const $$createType0 = User.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = Check.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = InlineCommentInput.createFrom;
const $$createType6 = $Create.Array($$createType5);
