// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * BlameLine represents a single line from git blame.
 */
export class BlameLine {
    /**
     * Full commit hash
     */
    "Hash": string;

    /**
     * Short commit hash (7 chars)
     */
    "ShortHash": string;
    "Author": string;
    "AuthorMail": string;

    /**
     * Unix timestamp as string
     */
    "Date": string;

    /**
     * Line number in current file
     */
    "LineNumber": number;

    /**
     * Original line number in commit
     */
    "OrigLine": number;
    "Content": string;

    /** Creates a new BlameLine instance. */
    constructor($$source: Partial<BlameLine> = {}) {
        if (!("Hash" in $$source)) {
            this["Hash"] = "";
        }
        if (!("ShortHash" in $$source)) {
            this["ShortHash"] = "";
        }
        if (!("Author" in $$source)) {
            this["Author"] = "";
        }
        if (!("AuthorMail" in $$source)) {
            this["AuthorMail"] = "";
        }
        if (!("Date" in $$source)) {
            this["Date"] = "";
        }
        if (!("LineNumber" in $$source)) {
            this["LineNumber"] = 0;
        }
        if (!("OrigLine" in $$source)) {
            this["OrigLine"] = 0;
        }
        if (!("Content" in $$source)) {
            this["Content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlameLine instance from a string or object.
     */
    static createFrom($$source: any = {}): BlameLine {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BlameLine($$parsedSource as Partial<BlameLine>);
    }
}

/**
 * Branch represents a git branch.
 */
export class Branch {
    "Name": string;
    "IsRemote": boolean;
    "IsCurrent": boolean;
    "IsTracking": boolean;
    "Upstream": string;
    "Ahead": number;
    "Behind": number;

    /**
     * Short hash of last commit
     */
    "LastCommit": string;

    /**
     * Subject of last commit
     */
    "LastMsg": string;

    /** Creates a new Branch instance. */
    constructor($$source: Partial<Branch> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("IsRemote" in $$source)) {
            this["IsRemote"] = false;
        }
        if (!("IsCurrent" in $$source)) {
            this["IsCurrent"] = false;
        }
        if (!("IsTracking" in $$source)) {
            this["IsTracking"] = false;
        }
        if (!("Upstream" in $$source)) {
            this["Upstream"] = "";
        }
        if (!("Ahead" in $$source)) {
            this["Ahead"] = 0;
        }
        if (!("Behind" in $$source)) {
            this["Behind"] = 0;
        }
        if (!("LastCommit" in $$source)) {
            this["LastCommit"] = "";
        }
        if (!("LastMsg" in $$source)) {
            this["LastMsg"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Branch instance from a string or object.
     */
    static createFrom($$source: any = {}): Branch {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Branch($$parsedSource as Partial<Branch>);
    }
}

/**
 * ChangeStats holds file count and line change stats.
 */
export class ChangeStats {
    "Files": number;
    "Insertions": number;
    "Deletions": number;

    /**
     * Untracked files (no +/- available)
     */
    "Untracked": number;

    /** Creates a new ChangeStats instance. */
    constructor($$source: Partial<ChangeStats> = {}) {
        if (!("Files" in $$source)) {
            this["Files"] = 0;
        }
        if (!("Insertions" in $$source)) {
            this["Insertions"] = 0;
        }
        if (!("Deletions" in $$source)) {
            this["Deletions"] = 0;
        }
        if (!("Untracked" in $$source)) {
            this["Untracked"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChangeStats instance from a string or object.
     */
    static createFrom($$source: any = {}): ChangeStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChangeStats($$parsedSource as Partial<ChangeStats>);
    }
}

/**
 * ChangedFile represents a file changed in a commit.
 */
export class ChangedFile {
    "Status": FileStatus;
    "Path": string;

    /**
     * For renames
     */
    "OldPath": string;
    "Binary": boolean;
    "Insertions": number;
    "Deletions": number;

    /** Creates a new ChangedFile instance. */
    constructor($$source: Partial<ChangedFile> = {}) {
        if (!("Status" in $$source)) {
            this["Status"] = FileStatus.$zero;
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("OldPath" in $$source)) {
            this["OldPath"] = "";
        }
        if (!("Binary" in $$source)) {
            this["Binary"] = false;
        }
        if (!("Insertions" in $$source)) {
            this["Insertions"] = 0;
        }
        if (!("Deletions" in $$source)) {
            this["Deletions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChangedFile instance from a string or object.
     */
    static createFrom($$source: any = {}): ChangedFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChangedFile($$parsedSource as Partial<ChangedFile>);
    }
}

/**
 * Commit is a plain-data commit record, free of any UI/layout state.
 */
export class Commit {
    "Hash": string;
    "ShortHash": string;
    "Message": string;
    "Author": string;
    "Date": time$0.Time;
    "Parents": string[];
    "Refs": string[];
    "Branch": string;
    "IsMerge": boolean;
    "IsStash": boolean;
    "Ahead": number;
    "Behind": number;

    /** Creates a new Commit instance. */
    constructor($$source: Partial<Commit> = {}) {
        if (!("Hash" in $$source)) {
            this["Hash"] = "";
        }
        if (!("ShortHash" in $$source)) {
            this["ShortHash"] = "";
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("Author" in $$source)) {
            this["Author"] = "";
        }
        if (!("Date" in $$source)) {
            this["Date"] = null;
        }
        if (!("Parents" in $$source)) {
            this["Parents"] = [];
        }
        if (!("Refs" in $$source)) {
            this["Refs"] = [];
        }
        if (!("Branch" in $$source)) {
            this["Branch"] = "";
        }
        if (!("IsMerge" in $$source)) {
            this["IsMerge"] = false;
        }
        if (!("IsStash" in $$source)) {
            this["IsStash"] = false;
        }
        if (!("Ahead" in $$source)) {
            this["Ahead"] = 0;
        }
        if (!("Behind" in $$source)) {
            this["Behind"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Commit instance from a string or object.
     */
    static createFrom($$source: any = {}): Commit {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Parents" in $$parsedSource) {
            $$parsedSource["Parents"] = $$createField5_0($$parsedSource["Parents"]);
        }
        if ("Refs" in $$parsedSource) {
            $$parsedSource["Refs"] = $$createField6_0($$parsedSource["Refs"]);
        }
        return new Commit($$parsedSource as Partial<Commit>);
    }
}

/**
 * CommitDetail contains detailed commit information.
 */
export class CommitDetail {
    "Hash": string;
    "ShortHash": string;
    "Subject": string;
    "Body": string;
    "Author": string;
    "AuthorEmail": string;
    "AuthorDate": time$0.Time;
    "Committer": string;
    "CommitterEmail": string;
    "CommitterDate": time$0.Time;
    "Parents": string[];

    /**
     * Subject lines of parent commits
     */
    "ParentSubjects": string[];
    "Refs": string[];

    /**
     * Branches containing this commit
     */
    "Branches": string[];
    "Stats": CommitStats;
    "Files": ChangedFile[];
    "GPGStatus": GPGSignature;

    /** Creates a new CommitDetail instance. */
    constructor($$source: Partial<CommitDetail> = {}) {
        if (!("Hash" in $$source)) {
            this["Hash"] = "";
        }
        if (!("ShortHash" in $$source)) {
            this["ShortHash"] = "";
        }
        if (!("Subject" in $$source)) {
            this["Subject"] = "";
        }
        if (!("Body" in $$source)) {
            this["Body"] = "";
        }
        if (!("Author" in $$source)) {
            this["Author"] = "";
        }
        if (!("AuthorEmail" in $$source)) {
            this["AuthorEmail"] = "";
        }
        if (!("AuthorDate" in $$source)) {
            this["AuthorDate"] = null;
        }
        if (!("Committer" in $$source)) {
            this["Committer"] = "";
        }
        if (!("CommitterEmail" in $$source)) {
            this["CommitterEmail"] = "";
        }
        if (!("CommitterDate" in $$source)) {
            this["CommitterDate"] = null;
        }
        if (!("Parents" in $$source)) {
            this["Parents"] = [];
        }
        if (!("ParentSubjects" in $$source)) {
            this["ParentSubjects"] = [];
        }
        if (!("Refs" in $$source)) {
            this["Refs"] = [];
        }
        if (!("Branches" in $$source)) {
            this["Branches"] = [];
        }
        if (!("Stats" in $$source)) {
            this["Stats"] = (new CommitStats());
        }
        if (!("Files" in $$source)) {
            this["Files"] = [];
        }
        if (!("GPGStatus" in $$source)) {
            this["GPGStatus"] = (new GPGSignature());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): CommitDetail {
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType0;
        const $$createField12_0 = $$createType0;
        const $$createField13_0 = $$createType0;
        const $$createField14_0 = $$createType1;
        const $$createField15_0 = $$createType3;
        const $$createField16_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Parents" in $$parsedSource) {
            $$parsedSource["Parents"] = $$createField10_0($$parsedSource["Parents"]);
        }
        if ("ParentSubjects" in $$parsedSource) {
            $$parsedSource["ParentSubjects"] = $$createField11_0($$parsedSource["ParentSubjects"]);
        }
        if ("Refs" in $$parsedSource) {
            $$parsedSource["Refs"] = $$createField12_0($$parsedSource["Refs"]);
        }
        if ("Branches" in $$parsedSource) {
            $$parsedSource["Branches"] = $$createField13_0($$parsedSource["Branches"]);
        }
        if ("Stats" in $$parsedSource) {
            $$parsedSource["Stats"] = $$createField14_0($$parsedSource["Stats"]);
        }
        if ("Files" in $$parsedSource) {
            $$parsedSource["Files"] = $$createField15_0($$parsedSource["Files"]);
        }
        if ("GPGStatus" in $$parsedSource) {
            $$parsedSource["GPGStatus"] = $$createField16_0($$parsedSource["GPGStatus"]);
        }
        return new CommitDetail($$parsedSource as Partial<CommitDetail>);
    }
}

/**
 * CommitStats contains commit statistics.
 */
export class CommitStats {
    "FilesChanged": number;
    "Insertions": number;
    "Deletions": number;

    /** Creates a new CommitStats instance. */
    constructor($$source: Partial<CommitStats> = {}) {
        if (!("FilesChanged" in $$source)) {
            this["FilesChanged"] = 0;
        }
        if (!("Insertions" in $$source)) {
            this["Insertions"] = 0;
        }
        if (!("Deletions" in $$source)) {
            this["Deletions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitStats instance from a string or object.
     */
    static createFrom($$source: any = {}): CommitStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommitStats($$parsedSource as Partial<CommitStats>);
    }
}

/**
 * ConflictRegion represents a single conflict region in a file.
 */
export class ConflictRegion {
    /**
     * Line number where conflict starts (0-indexed)
     */
    "StartLine": number;

    /**
     * Line number where conflict ends (0-indexed)
     */
    "EndLine": number;

    /**
     * Lines between <<<<<<< and |||||||
     */
    "OursLines": string[];

    /**
     * Lines between ||||||| and =======
     */
    "BaseLines": string[];

    /**
     * Lines between ======= and >>>>>>>
     */
    "TheirsLines": string[];

    /**
     * Usually "HEAD" or branch name
     */
    "OursLabel": string;

    /**
     * Branch/commit name
     */
    "TheirsLabel": string;

    /**
     * Whether this conflict has a base section (diff3)
     */
    "HasBase": boolean;

    /** Creates a new ConflictRegion instance. */
    constructor($$source: Partial<ConflictRegion> = {}) {
        if (!("StartLine" in $$source)) {
            this["StartLine"] = 0;
        }
        if (!("EndLine" in $$source)) {
            this["EndLine"] = 0;
        }
        if (!("OursLines" in $$source)) {
            this["OursLines"] = [];
        }
        if (!("BaseLines" in $$source)) {
            this["BaseLines"] = [];
        }
        if (!("TheirsLines" in $$source)) {
            this["TheirsLines"] = [];
        }
        if (!("OursLabel" in $$source)) {
            this["OursLabel"] = "";
        }
        if (!("TheirsLabel" in $$source)) {
            this["TheirsLabel"] = "";
        }
        if (!("HasBase" in $$source)) {
            this["HasBase"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictRegion instance from a string or object.
     */
    static createFrom($$source: any = {}): ConflictRegion {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("OursLines" in $$parsedSource) {
            $$parsedSource["OursLines"] = $$createField2_0($$parsedSource["OursLines"]);
        }
        if ("BaseLines" in $$parsedSource) {
            $$parsedSource["BaseLines"] = $$createField3_0($$parsedSource["BaseLines"]);
        }
        if ("TheirsLines" in $$parsedSource) {
            $$parsedSource["TheirsLines"] = $$createField4_0($$parsedSource["TheirsLines"]);
        }
        return new ConflictRegion($$parsedSource as Partial<ConflictRegion>);
    }
}

/**
 * ConflictState represents the current state of a merge/rebase conflict.
 */
export class ConflictState {
    "Type": ConflictType;
    "InProgress": boolean;

    /**
     * The branch being merged/rebased onto
     */
    "TargetBranch": string;

    /**
     * The branch being merged/rebased from
     */
    "SourceBranch": string;
    "Files": string[];

    /** Creates a new ConflictState instance. */
    constructor($$source: Partial<ConflictState> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = ConflictType.$zero;
        }
        if (!("InProgress" in $$source)) {
            this["InProgress"] = false;
        }
        if (!("TargetBranch" in $$source)) {
            this["TargetBranch"] = "";
        }
        if (!("SourceBranch" in $$source)) {
            this["SourceBranch"] = "";
        }
        if (!("Files" in $$source)) {
            this["Files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictState instance from a string or object.
     */
    static createFrom($$source: any = {}): ConflictState {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Files" in $$parsedSource) {
            $$parsedSource["Files"] = $$createField4_0($$parsedSource["Files"]);
        }
        return new ConflictState($$parsedSource as Partial<ConflictState>);
    }
}

/**
 * ConflictType represents the type of conflict operation in progress.
 */
export enum ConflictType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ConflictNone = 0,
    ConflictMerge = 1,
    ConflictRebase = 2,
    ConflictCherryPick = 3,
};

/**
 * DiffHunk represents a contiguous block of changes.
 */
export class DiffHunk {
    /**
     * @@ -start,count +start,count @@ context
     */
    "Header": string;

    /**
     * Starting line in old file
     */
    "OldStart": number;

    /**
     * Number of lines from old file
     */
    "OldCount": number;

    /**
     * Starting line in new file
     */
    "NewStart": number;

    /**
     * Number of lines in new file
     */
    "NewCount": number;

    /**
     * Lines in this hunk
     */
    "Lines": (DiffLine | null)[];

    /**
     * Entire hunk selected
     */
    "Selected": boolean;

    /**
     * Whether hunk is expanded in view
     */
    "Expanded": boolean;

    /** Creates a new DiffHunk instance. */
    constructor($$source: Partial<DiffHunk> = {}) {
        if (!("Header" in $$source)) {
            this["Header"] = "";
        }
        if (!("OldStart" in $$source)) {
            this["OldStart"] = 0;
        }
        if (!("OldCount" in $$source)) {
            this["OldCount"] = 0;
        }
        if (!("NewStart" in $$source)) {
            this["NewStart"] = 0;
        }
        if (!("NewCount" in $$source)) {
            this["NewCount"] = 0;
        }
        if (!("Lines" in $$source)) {
            this["Lines"] = [];
        }
        if (!("Selected" in $$source)) {
            this["Selected"] = false;
        }
        if (!("Expanded" in $$source)) {
            this["Expanded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffHunk instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffHunk {
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Lines" in $$parsedSource) {
            $$parsedSource["Lines"] = $$createField5_0($$parsedSource["Lines"]);
        }
        return new DiffHunk($$parsedSource as Partial<DiffHunk>);
    }
}

/**
 * DiffLine represents a single line in a diff.
 */
export class DiffLine {
    "Type": LineType;
    "Content": string;

    /**
     * Line number in old file (0 if added)
     */
    "OldLineNo": number;

    /**
     * Line number in new file (0 if removed)
     */
    "NewLineNo": number;

    /**
     * Whether this line is selected for staging
     */
    "Selected": boolean;

    /** Creates a new DiffLine instance. */
    constructor($$source: Partial<DiffLine> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = LineType.$zero;
        }
        if (!("Content" in $$source)) {
            this["Content"] = "";
        }
        if (!("OldLineNo" in $$source)) {
            this["OldLineNo"] = 0;
        }
        if (!("NewLineNo" in $$source)) {
            this["NewLineNo"] = 0;
        }
        if (!("Selected" in $$source)) {
            this["Selected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffLine instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffLine {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffLine($$parsedSource as Partial<DiffLine>);
    }
}

/**
 * FileDiff represents all changes to a single file.
 */
export class FileDiff {
    /**
     * File path
     */
    "Path": string;

    /**
     * Old path (for renames)
     */
    "OldPath": string;

    /**
     * Added, Modified, Deleted, Renamed
     */
    "Status": FileStatus;

    /**
     * All hunks in this file
     */
    "Hunks": (DiffHunk | null)[];

    /**
     * True if binary file
     */
    "Binary": boolean;

    /**
     * True if this is a new file
     */
    "NewFile": boolean;

    /**
     * True if this file was deleted
     */
    "Deleted": boolean;

    /** Creates a new FileDiff instance. */
    constructor($$source: Partial<FileDiff> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("OldPath" in $$source)) {
            this["OldPath"] = "";
        }
        if (!("Status" in $$source)) {
            this["Status"] = FileStatus.$zero;
        }
        if (!("Hunks" in $$source)) {
            this["Hunks"] = [];
        }
        if (!("Binary" in $$source)) {
            this["Binary"] = false;
        }
        if (!("NewFile" in $$source)) {
            this["NewFile"] = false;
        }
        if (!("Deleted" in $$source)) {
            this["Deleted"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): FileDiff {
        const $$createField3_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Hunks" in $$parsedSource) {
            $$parsedSource["Hunks"] = $$createField3_0($$parsedSource["Hunks"]);
        }
        return new FileDiff($$parsedSource as Partial<FileDiff>);
    }
}

/**
 * FileLogEntry represents a commit that affected a file.
 */
export class FileLogEntry {
    "Hash": string;
    "ShortHash": string;
    "Subject": string;
    "Author": string;
    "Date": string;
    "Insertions": number;
    "Deletions": number;

    /** Creates a new FileLogEntry instance. */
    constructor($$source: Partial<FileLogEntry> = {}) {
        if (!("Hash" in $$source)) {
            this["Hash"] = "";
        }
        if (!("ShortHash" in $$source)) {
            this["ShortHash"] = "";
        }
        if (!("Subject" in $$source)) {
            this["Subject"] = "";
        }
        if (!("Author" in $$source)) {
            this["Author"] = "";
        }
        if (!("Date" in $$source)) {
            this["Date"] = "";
        }
        if (!("Insertions" in $$source)) {
            this["Insertions"] = 0;
        }
        if (!("Deletions" in $$source)) {
            this["Deletions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileLogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FileLogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileLogEntry($$parsedSource as Partial<FileLogEntry>);
    }
}

/**
 * FileStatus represents the status of a file in the working tree.
 */
export enum FileStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * 0 = no status / unchanged
     */
    FileUnchanged = 0,

    /**
     * 1
     */
    FileModified = 1,

    /**
     * 2
     */
    FileAdded = 2,

    /**
     * 3
     */
    FileDeleted = 3,

    /**
     * 4
     */
    FileRenamed = 4,

    /**
     * 5
     */
    FileCopied = 5,

    /**
     * 6
     */
    FileUntracked = 6,

    /**
     * 7
     */
    FileIgnored = 7,

    /**
     * 8
     */
    FileConflict = 8,
};

/**
 * GPGSignature contains GPG signature verification info.
 */
export class GPGSignature {
    "Signed": boolean;
    "Valid": boolean;
    "KeyID": string;
    "Signer": string;
    "TrustLevel": string;

    /** Creates a new GPGSignature instance. */
    constructor($$source: Partial<GPGSignature> = {}) {
        if (!("Signed" in $$source)) {
            this["Signed"] = false;
        }
        if (!("Valid" in $$source)) {
            this["Valid"] = false;
        }
        if (!("KeyID" in $$source)) {
            this["KeyID"] = "";
        }
        if (!("Signer" in $$source)) {
            this["Signer"] = "";
        }
        if (!("TrustLevel" in $$source)) {
            this["TrustLevel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GPGSignature instance from a string or object.
     */
    static createFrom($$source: any = {}): GPGSignature {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GPGSignature($$parsedSource as Partial<GPGSignature>);
    }
}

/**
 * Graph is the commit graph as plain data (newest first) with a hash lookup.
 */
export class Graph {
    "Commits": (Commit | null)[];
    "CommitMap": { [_ in string]?: Commit | null };
    "CurrentBranch": string;

    /** Creates a new Graph instance. */
    constructor($$source: Partial<Graph> = {}) {
        if (!("Commits" in $$source)) {
            this["Commits"] = [];
        }
        if (!("CommitMap" in $$source)) {
            this["CommitMap"] = {};
        }
        if (!("CurrentBranch" in $$source)) {
            this["CurrentBranch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Graph instance from a string or object.
     */
    static createFrom($$source: any = {}): Graph {
        const $$createField0_0 = $$createType13;
        const $$createField1_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Commits" in $$parsedSource) {
            $$parsedSource["Commits"] = $$createField0_0($$parsedSource["Commits"]);
        }
        if ("CommitMap" in $$parsedSource) {
            $$parsedSource["CommitMap"] = $$createField1_0($$parsedSource["CommitMap"]);
        }
        return new Graph($$parsedSource as Partial<Graph>);
    }
}

/**
 * LineType represents the type of a diff line.
 */
export enum LineType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * Unchanged line (starts with space)
     */
    LineContext = 0,

    /**
     * Added line (starts with +)
     */
    LineAdded = 1,

    /**
     * Removed line (starts with -)
     */
    LineRemoved = 2,

    /**
     * Hunk header (@@ ... @@)
     */
    LineHeader = 3,
};

/**
 * Stash represents a stash entry.
 */
export class Stash {
    /**
     * stash@{0}, stash@{1}, etc.
     */
    "Index": number;

    /**
     * Branch where stash was created
     */
    "Branch": string;

    /**
     * Stash message
     */
    "Message": string;

    /** Creates a new Stash instance. */
    constructor($$source: Partial<Stash> = {}) {
        if (!("Index" in $$source)) {
            this["Index"] = 0;
        }
        if (!("Branch" in $$source)) {
            this["Branch"] = "";
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stash instance from a string or object.
     */
    static createFrom($$source: any = {}): Stash {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Stash($$parsedSource as Partial<Stash>);
    }
}

/**
 * StatusEntry represents a file in the working tree status.
 */
export class StatusEntry {
    "Path": string;

    /**
     * For renames
     */
    "OldPath": string;

    /**
     * Status in index (staged)
     */
    "IndexStatus": FileStatus;

    /**
     * Status in working tree (unstaged)
     */
    "WorkStatus": FileStatus;
    "IsStaged": boolean;
    "IsUntracked": boolean;
    "IsConflict": boolean;

    /** Creates a new StatusEntry instance. */
    constructor($$source: Partial<StatusEntry> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("OldPath" in $$source)) {
            this["OldPath"] = "";
        }
        if (!("IndexStatus" in $$source)) {
            this["IndexStatus"] = FileStatus.$zero;
        }
        if (!("WorkStatus" in $$source)) {
            this["WorkStatus"] = FileStatus.$zero;
        }
        if (!("IsStaged" in $$source)) {
            this["IsStaged"] = false;
        }
        if (!("IsUntracked" in $$source)) {
            this["IsUntracked"] = false;
        }
        if (!("IsConflict" in $$source)) {
            this["IsConflict"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): StatusEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusEntry($$parsedSource as Partial<StatusEntry>);
    }
}

/**
 * Tag represents a git tag.
 */
export class Tag {
    "Name": string;
    "Hash": string;
    "Message": string;
    "Tagger": string;
    "IsAnnotated": boolean;

    /** Creates a new Tag instance. */
    constructor($$source: Partial<Tag> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Hash" in $$source)) {
            this["Hash"] = "";
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("Tagger" in $$source)) {
            this["Tagger"] = "";
        }
        if (!("IsAnnotated" in $$source)) {
            this["IsAnnotated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tag instance from a string or object.
     */
    static createFrom($$source: any = {}): Tag {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tag($$parsedSource as Partial<Tag>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = CommitStats.createFrom;
const $$createType2 = ChangedFile.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = GPGSignature.createFrom;
const $$createType5 = DiffLine.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = DiffHunk.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = Commit.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Map($Create.Any, $$createType12);
