<script setup lang="ts">
import { computed, ref } from 'vue'
import GraphSvg from '../../components/graph/GraphSvg.vue'
import { graphRailWidth } from '../../components/graph/graphGeometry'
import type { GraphLayout } from '../../bindings/github.com/atterpac/ichi/desktop/services'
import type { BendStyle, CrossingStyle, NodeShape } from '../../components/graph/svg/types'
import layouts from './routed-fixtures.json'
const props = defineProps<{
  height: number
  bend: BendStyle
  crossing: CrossingStyle
  shape: NodeShape
}>()
const selected = ref('Crossings and converging parents')
const graph = computed(() => (layouts as unknown as Record<string, GraphLayout>)[selected.value]!)
const width = computed(() => graphRailWidth(graph.value.LaneCount))
const appearance = computed(() => ({
  'graph.authorAvatars': false,
  'graph.renderStyle': 'classic' as const,
  'graph.nodeGlyph': props.shape,
  'graph.bendStyle': props.bend === 'square' ? ('elbow' as const) : props.bend,
  'graph.collisionStyle': props.crossing === 'continuous' ? ('cross' as const) : props.crossing,
}))
</script>

<template>
  <section class="panel routed-examples">
    <div class="section-head">
      <div>
        <h2>03 / Actual router output</h2>
        <p>Generated by the Go regression fixtures and drawn by the in-app renderer.</p>
      </div>
      <select v-model="selected" aria-label="Routing regression fixture">
        <option v-for="(_, name) in layouts" :key="name">{{ name }}</option>
      </select>
    </div>
    <div class="routed-scroll">
      <div class="routed-history" :style="{ minWidth: `${width + 280}px` }">
        <GraphSvg
          :rows="graph.Rows"
          :lane-count="graph.LaneCount"
          :row-height="height"
          :appearance="appearance"
        />
        <div class="routed-labels">
          <div
            v-for="row in graph.Rows"
            :key="row.Commit!.Hash"
            class="routed-row"
            :style="{ height: `${height}px` }"
          >
            <strong>{{ row.Commit!.Message }}</strong
            ><code>→ {{ row.Commit!.Parents?.join(', ') || 'root' }}</code>
          </div>
        </div>
      </div>
    </div>
    <p class="footnote">
      Each parent connection retains its rail and color. Multiple merge arms use separate tracks;
      crossings keep unrelated rails separate. Bend, crossing, shape, and row-height controls apply
      here too.
    </p>
  </section>
</template>

<style scoped>
.routed-examples {
  --surface: var(--graph-surface);
  --accent: var(--graph-accent);
  --lane-0: #48bea1;
  --lane-1: #e1ac54;
  --lane-2: #64a7ed;
  --lane-3: #a592f5;
  --lane-4: #d284c6;
}
.routed-scroll {
  overflow: auto;
  padding: 16px;
}
.routed-history {
  display: flex;
}
.routed-history :deep(.graph-svg) {
  position: relative;
  inset: auto;
  flex-shrink: 0;
}
.routed-labels {
  flex: 1;
}
.routed-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 24px;
  padding: 0 16px;
  border-bottom: 1px solid var(--border);
  font-size: 12px;
}
.routed-row strong {
  font-weight: 500;
}
.routed-row code {
  color: var(--muted);
  font-size: 11px;
}
</style>
