import { createApp } from 'vue'
import App from './App.vue'
import './theme/fonts.css'
import './theme/tokens.css'
import './theme/themes.css'
import './theme/base.css'
import './theme/primitives.css'
import './theme/shell.css'
import './theme/states.css'
import './theme/views/graph.css'
import './theme/overlays/settings.css'
import './theme/views/inspect.css'
import './theme/overlays/menus.css'
import './theme/overlays/toasts.css'
import './theme/views/changes.css'
import './theme/views/conflicts.css'
import './theme/views/diff.css'
import './theme/views/refs.css'
import './theme/overlays/finder.css'

createApp(App).mount('#app')
