// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Repo is a saved git repository the user can quickly switch between.
 */
export class Repo {
    /**
     * Name is the human-readable label shown in the repo switcher.
     */
    "Name": string;

    /**
     * Path is the absolute path to the repository working tree.
     */
    "Path": string;

    /**
     * Alias is an optional short handle for ":repo <alias>".
     */
    "Alias": string;

    /** Creates a new Repo instance. */
    constructor($$source: Partial<Repo> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Alias" in $$source)) {
            this["Alias"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Repo instance from a string or object.
     */
    static createFrom($$source: any = {}): Repo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Repo($$parsedSource as Partial<Repo>);
    }
}
