#!/usr/bin/env node
// Generates src/theme/themes.css and src/theme/themes.ts from the dado theme defs.
// Source of truth: <dado>/theme/themes/defs/*.yaml (override location with DADO_DIR).
// Run: pnpm gen:themes — commit the generated output.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const frontendDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const defsDir = process.env.DADO_DIR
  ? join(process.env.DADO_DIR, 'theme/themes/defs')
  : resolve(frontendDir, '../../../dado/theme/themes/defs')

const DEFAULT_THEME = 'tokyonight-night'

const LABELS = {
  tokyonight: 'Tokyo Night',
  github: 'GitHub',
  rosepine: 'Rosé Pine',
  onedark: 'One Dark',
  onelight: 'One Light',
  catppuccin: 'Catppuccin',
}
const LABEL_OVERRIDES = {
  'tokyonight-night': 'Tokyo Night',
}

function parseDef(text) {
  const name = text.match(/^name:\s*(\S+)/m)?.[1]
  const colors = {}
  for (const [, key, hex] of text.matchAll(/^\s{2}(\w+):\s*"(#[0-9a-fA-F]{6})"/gm)) {
    colors[key] = hex.toLowerCase()
  }
  return { name, colors }
}

function rgb(hex) {
  return [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16))
}

function toHex(channels) {
  return `#${channels.map((c) => Math.round(Math.max(0, Math.min(255, c))).toString(16).padStart(2, '0')).join('')}`
}

function mix(a, b, amount) {
  const ca = rgb(a)
  const cb = rgb(b)
  return toHex(ca.map((c, i) => c + (cb[i] - c) * amount))
}

function isLight(hex) {
  const [r, g, b] = rgb(hex)
  return 0.2126 * r + 0.7152 * g + 0.0722 * b > 128
}

function luminance(hex) {
  const [r, g, b] = rgb(hex).map((c) => {
    c /= 255
    return c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4
  })
  return 0.2126 * r + 0.7152 * g + 0.0722 * b
}

function contrast(a, b) {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x)
  return (hi + 0.05) / (lo + 0.05)
}

// Smallest mix of `from` toward `to` that satisfies `ok`.
function mixUntil(from, to, ok) {
  let lo = 0
  let hi = 1
  for (let i = 0; i < 24; i++) {
    const mid = (lo + hi) / 2
    if (ok(mix(from, to, mid))) hi = mid
    else lo = mid
  }
  return mix(from, to, hi)
}

// Muted text should sit at ~4–5.5:1 against the surface: below that it's
// illegible (nord), above it stops reading as muted (atterpac).
function tuneMut(mut, surface, text) {
  const c = contrast(mut, surface)
  if (c < 4) return mixUntil(mut, text, (h) => contrast(h, surface) >= 4)
  if (c > 5.5) return mixUntil(mut, surface, (h) => contrast(h, surface) <= 5.5)
  return mut
}

function label(id) {
  if (LABEL_OVERRIDES[id]) return LABEL_OVERRIDES[id]
  return id
    .split('-')
    .map((part) => LABELS[part] ?? part[0].toUpperCase() + part.slice(1))
    .join(' ')
}

const themes = readdirSync(defsDir)
  .filter((file) => file.endsWith('.yaml'))
  .map((file) => parseDef(readFileSync(join(defsDir, file), 'utf8')))
  .filter((def) => def.name && def.colors.bg)
  .sort((a, b) => a.name.localeCompare(b.name))

if (!themes.some((t) => t.name === DEFAULT_THEME)) {
  throw new Error(`default theme "${DEFAULT_THEME}" not found in ${defsDir}`)
}

function cssBlock({ name, colors: c }) {
  const light = isLight(c.bg)
  const selector = name === DEFAULT_THEME ? `:root,\n.theme-${name}` : `.theme-${name}`
  // Layering must be monotonic regardless of how the def orders its bg tones
  // (rosepine ships surface darker than bg): dark stacks lightest-on-top,
  // light keeps the lightest tone for cards with the page slightly darker.
  const layers = [c.bg_dark, c.bg, c.bg_light].sort((a, b) => luminance(a) - luminance(b))
  const [bg, surface, surface2] = light ? [layers[1], layers[2], layers[0]] : layers
  const head = light ? mix(c.fg, '#000000', 0.35) : mix(c.fg, '#ffffff', 0.3)
  const accentInk = light ? surface : bg
  const mut = tuneMut(c.fg_dim, surface, c.fg)
  const vars = [
    `--bg:${bg};--surface:${surface};--surface-2:${surface2};`,
    `--text:${c.fg};--text-mut:${mut};--head:${head};`,
    `--accent:${c.accent};--accent-ink:${accentInk};`,
    `--green:${c.success};--orange:${c.warning};--red:${c.error};--purple:${c.accent_dim};--cyan:${c.info};--star:${c.warning};`,
  ]
  if (light) {
    vars.push('--shadow-1: 0 1px 2px rgba(30,35,60,.1);--shadow-2: 0 8px 24px -4px rgba(30,35,60,.18);')
  } else {
    // Black-on-black shadows carry no elevation cue; a faint inset top
    // highlight does the work on dark surfaces.
    vars.push('--shadow-1: 0 1px 2px rgba(0,0,0,.35), inset 0 1px 0 rgba(255,255,255,.04);--shadow-2: 0 8px 24px -4px rgba(0,0,0,.5), inset 0 1px 0 rgba(255,255,255,.05);')
  }
  return `${selector} {\n  ${vars.join('\n  ')}\n}`
}

const cssHeader = '/* Generated by scripts/generate-themes.mjs from dado theme defs. DO NOT EDIT. */'
const ordered = [themes.find((t) => t.name === DEFAULT_THEME), ...themes.filter((t) => t.name !== DEFAULT_THEME)]
writeFileSync(join(frontendDir, 'src/theme/themes.css'), `${cssHeader}\n\n${ordered.map(cssBlock).join('\n\n')}\n`)

const tsEntries = themes
  .map(({ name, colors }) => `  { id: '${name}', label: '${label(name)}', light: ${isLight(colors.bg)} },`)
  .join('\n')
const ts = `// Generated by scripts/generate-themes.mjs from dado theme defs. DO NOT EDIT.

export const THEMES = [
${tsEntries}
] as const

export type ThemeId = (typeof THEMES)[number]['id']

export const DEFAULT_THEME: ThemeId = '${DEFAULT_THEME}'

export function isThemeId(value: unknown): value is ThemeId {
  return THEMES.some((theme) => theme.id === value)
}

export function isLightTheme(id: string): boolean {
  return THEMES.find((theme) => theme.id === id)?.light ?? false
}
`
writeFileSync(join(frontendDir, 'src/theme/themes.ts'), ts)

console.log(`generated ${themes.length} themes from ${defsDir}`)
