import { beforeEach, describe, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ sync: vi.fn(), list: vi.fn(), effective: vi.fn() }))
vi.mock('../bindings/github.com/atterpac/ichi/desktop/services', () => ({ RepoService: { SyncWorkspaceProfiles: mocks.sync, ListGitProfiles: mocks.list, RepositoryProfile: mocks.effective } }))
beforeEach(() => {
 vi.resetModules()
 vi.clearAllMocks()
 const saved = new Map<string,string>()
 vi.stubGlobal('localStorage', { getItem: (k: string) => saved.get(k) ?? null, setItem: (k: string,v: string) => saved.set(k,v) })
 mocks.sync.mockResolvedValue(undefined)
 mocks.list.mockResolvedValue({ Profiles: [], Warnings: [] })
 mocks.effective.mockResolvedValue(null)
})
describe('Git workspace identity assignments', () => {
 it('projects identities to every repo and restores defaults when unassigned', async () => {
  const ws = (await import('../composables/useWorkspaces')).useWorkspaces()
  ws.saveRepo('/a','A','personal'); ws.saveRepo('/b','B','personal')
  const profiles = (await import('../composables/useGitProfiles')).useGitProfiles()
  await profiles.ready()
  await profiles.assign('personal','global')
  expect(mocks.sync).toHaveBeenLastCalledWith({ '/a':'global', '/b':'global' })
  expect(JSON.parse(localStorage.getItem('ichi.desktop.workspaces.v1')!).workspaces[0].profileId).toBe('global')
  await profiles.assign('personal','')
  expect(mocks.sync).toHaveBeenLastCalledWith({})
 })
 it('rolls back a failed assignment instead of displaying an unapplied profile', async () => {
  const ws = (await import('../composables/useWorkspaces')).useWorkspaces()
  ws.saveRepo('/a','A','personal')
  const profiles = (await import('../composables/useGitProfiles')).useGitProfiles()
  await profiles.ready()
  mocks.sync.mockRejectedValueOnce(new Error('profile missing'))
  await expect(profiles.assign('personal','/missing')).rejects.toThrow('profile missing')
  expect(ws.state.workspaces[0]!.profileId).toBeUndefined()
  expect(mocks.sync).toHaveBeenLastCalledWith({})
  expect(profiles.state.syncing).toBe(false)
 })
})
