// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function CommandNames(): $CancellablePromise<string[]> {
    return $Call.ByID(2169501584).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Complete(input: string): $CancellablePromise<string[]> {
    return $Call.ByID(1322361040, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListBranchNames(prefix: string): $CancellablePromise<string[]> {
    return $Call.ByID(1380617393, prefix).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListFiles(prefix: string): $CancellablePromise<string[]> {
    return $Call.ByID(3712860306, prefix).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListRecentCommitHashes(prefix: string, limit: number): $CancellablePromise<string[]> {
    return $Call.ByID(2991475613, prefix, limit).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListRemotes(prefix: string): $CancellablePromise<string[]> {
    return $Call.ByID(4248762358, prefix).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListStashEntries(prefix: string): $CancellablePromise<string[]> {
    return $Call.ByID(2071900092, prefix).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListTagNames(prefix: string): $CancellablePromise<string[]> {
    return $Call.ByID(2682646595, prefix).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Suggest(input: string): $CancellablePromise<string> {
    return $Call.ByID(3465013503, input);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
