// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "../../internal/git/models.js";

export function CommitDiff(hash: string): $CancellablePromise<string> {
    return $Call.ByID(4241559888, hash);
}

export function DiffBetween($from: string, to: string): $CancellablePromise<string> {
    return $Call.ByID(1091634255, $from, to);
}

export function DiffStats($from: string, to: string): $CancellablePromise<string> {
    return $Call.ByID(1288001228, $from, to);
}

export function DiscardHunk(path: string, hunk: git$0.DiffHunk | null): $CancellablePromise<void> {
    return $Call.ByID(2380773616, path, hunk);
}

export function FileDiff(hash: string, path: string): $CancellablePromise<string> {
    return $Call.ByID(448168455, hash, path);
}

export function ParseDiff(raw: string): $CancellablePromise<(git$0.FileDiff | null)[]> {
    return $Call.ByID(2252851846, raw).then(($result: any) => {
        return $$createType2($result);
    });
}

export function StageHunk(path: string, hunk: git$0.DiffHunk | null): $CancellablePromise<void> {
    return $Call.ByID(538212720, path, hunk);
}

export function StageLines(path: string, hunk: git$0.DiffHunk | null, lines: (git$0.DiffLine | null)[]): $CancellablePromise<void> {
    return $Call.ByID(1993002379, path, hunk, lines);
}

export function StagedDiff(): $CancellablePromise<string> {
    return $Call.ByID(1844281755);
}

export function StagedFileDiff(path: string): $CancellablePromise<string> {
    return $Call.ByID(1014444737, path);
}

export function UnstageHunk(path: string, hunk: git$0.DiffHunk | null): $CancellablePromise<void> {
    return $Call.ByID(3058782017, path, hunk);
}

export function UnstageLines(path: string, hunk: git$0.DiffHunk | null, lines: (git$0.DiffLine | null)[]): $CancellablePromise<void> {
    return $Call.ByID(11077732, path, hunk, lines);
}

export function WorkingDiff(): $CancellablePromise<string> {
    return $Call.ByID(3999577938);
}

export function WorkingFileDiff(path: string): $CancellablePromise<string> {
    return $Call.ByID(1481350648, path);
}

// Private type creation functions
const $$createType0 = git$0.FileDiff.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
