// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "../../internal/git/models.js";

export function ApplyHunkEdit(path: string, hunk: git$0.DiffHunk | null, replacement: string[]): $CancellablePromise<void> {
    return $Call.ByID(2609341442, path, hunk, replacement);
}

export function DiffBetween($from: string, to: string): $CancellablePromise<(git$0.FileDiff | null)[]> {
    return $Call.ByID(1091634255, $from, to).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * DiffBetweenFile returns only the selected file. An empty oldPath lets Git
 * discover the rename source from the comparison's summary, without reading
 * unrelated patches into the desktop process or bridge payload.
 */
export function DiffBetweenFile($from: string, to: string, path: string, oldPath: string): $CancellablePromise<git$0.FileDiff | null> {
    return $Call.ByID(511821633, $from, to, path, oldPath).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DiscardHunk(path: string, hunk: git$0.DiffHunk | null): $CancellablePromise<void> {
    return $Call.ByID(2380773616, path, hunk);
}

export function FileDiff(hash: string, path: string): $CancellablePromise<(git$0.FileDiff | null)[]> {
    return $Call.ByID(448168455, hash, path).then(($result: any) => {
        return $$createType2($result);
    });
}

export function LoadEditorFile(file: string): $CancellablePromise<string> {
    return $Call.ByID(3245092857, file);
}

export function SaveEditorFile(file: string, original: string, replacement: string): $CancellablePromise<void> {
    return $Call.ByID(3563504704, file, original, replacement);
}

export function StageHunk(path: string, hunk: git$0.DiffHunk | null): $CancellablePromise<void> {
    return $Call.ByID(538212720, path, hunk);
}

export function StageLines(path: string, hunk: git$0.DiffHunk | null, lines: (git$0.DiffLine | null)[]): $CancellablePromise<void> {
    return $Call.ByID(1993002379, path, hunk, lines);
}

export function UnstageHunk(path: string, hunk: git$0.DiffHunk | null): $CancellablePromise<void> {
    return $Call.ByID(3058782017, path, hunk);
}

export function UnstageLines(path: string, hunk: git$0.DiffHunk | null, lines: (git$0.DiffLine | null)[]): $CancellablePromise<void> {
    return $Call.ByID(11077732, path, hunk, lines);
}

/**
 * Diff reads return structured files. Patch text stays inside Go; all desktop
 * consumers receive the same parsed representation in one bridge call.
 */
export function WorktreeFile(path: string, oldPath: string, staged: boolean): $CancellablePromise<git$0.FileDiff | null> {
    return $Call.ByID(3953190521, path, oldPath, staged).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = git$0.FileDiff.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
