// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "../../internal/git/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DropCommit(hash: string): $CancellablePromise<void> {
    return $Call.ByID(784815965, hash);
}

export function GetCommitMessage(hash: string): $CancellablePromise<string> {
    return $Call.ByID(3005240585, hash);
}

export function IsCommitPushed(hash: string): $CancellablePromise<boolean> {
    return $Call.ByID(835241989, hash);
}

export function LoadCommit(hash: string): $CancellablePromise<git$0.CommitDetail | null> {
    return $Call.ByID(538336828, hash).then(($result: any) => {
        return $$createType1($result);
    });
}

export function LoadGraph(limit: number): $CancellablePromise<git$0.Graph | null> {
    return $Call.ByID(207611783, limit).then(($result: any) => {
        return $$createType3($result);
    });
}

export function LoadGraphLayout(limit: number): $CancellablePromise<$models.GraphLayout | null> {
    return $Call.ByID(3171989245, limit).then(($result: any) => {
        return $$createType5($result);
    });
}

export function LoadGraphStashes(): $CancellablePromise<(git$0.Commit | null)[]> {
    return $Call.ByID(1387277908).then(($result: any) => {
        return $$createType8($result);
    });
}

export function RenameCommit(hash: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(2613642366, hash, message);
}

export function SearchCommits(query: string, limit: number): $CancellablePromise<(git$0.Commit | null)[]> {
    return $Call.ByID(3800079149, query, limit).then(($result: any) => {
        return $$createType8($result);
    });
}

// Private type creation functions
const $$createType0 = git$0.CommitDetail.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = git$0.Graph.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.GraphLayout.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = git$0.Commit.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
