// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "../../internal/git/models.js";

export function Blame(file: string): $CancellablePromise<git$0.BlameLine[]> {
    return $Call.ByID(192581412, file).then(($result: any) => {
        return $$createType1($result);
    });
}

export function BlameAtCommit(file: string, hash: string): $CancellablePromise<git$0.BlameLine[]> {
    return $Call.ByID(1916093624, file, hash).then(($result: any) => {
        return $$createType1($result);
    });
}

export function FileContent(ref: string, file: string): $CancellablePromise<string> {
    return $Call.ByID(972447876, ref, file);
}

export function FileLog(file: string, limit: number): $CancellablePromise<git$0.FileLogEntry[]> {
    return $Call.ByID(3178337667, file, limit).then(($result: any) => {
        return $$createType3($result);
    });
}

export function WorkingFileContent(file: string): $CancellablePromise<string> {
    return $Call.ByID(3432377663, file);
}

// Private type creation functions
const $$createType0 = git$0.BlameLine.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = git$0.FileLogEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
