// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "../../internal/git/models.js";

export class ConflictFile {
    "Regions": (git$0.ConflictRegion | null)[];
    "Lines": string[];

    /** Creates a new ConflictFile instance. */
    constructor($$source: Partial<ConflictFile> = {}) {
        if (!("Regions" in $$source)) {
            this["Regions"] = [];
        }
        if (!("Lines" in $$source)) {
            this["Lines"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictFile instance from a string or object.
     */
    static createFrom($$source: any = {}): ConflictFile {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Regions" in $$parsedSource) {
            $$parsedSource["Regions"] = $$createField0_0($$parsedSource["Regions"]);
        }
        if ("Lines" in $$parsedSource) {
            $$parsedSource["Lines"] = $$createField1_0($$parsedSource["Lines"]);
        }
        return new ConflictFile($$parsedSource as Partial<ConflictFile>);
    }
}

export class GraphGlyph {
    "Kind": string;
    "ColorID": number;
    "CommitHash": string;
    "ConnectTop": boolean;
    "ConnectBottom": boolean;

    /** Creates a new GraphGlyph instance. */
    constructor($$source: Partial<GraphGlyph> = {}) {
        if (!("Kind" in $$source)) {
            this["Kind"] = "";
        }
        if (!("ColorID" in $$source)) {
            this["ColorID"] = 0;
        }
        if (!("CommitHash" in $$source)) {
            this["CommitHash"] = "";
        }
        if (!("ConnectTop" in $$source)) {
            this["ConnectTop"] = false;
        }
        if (!("ConnectBottom" in $$source)) {
            this["ConnectBottom"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphGlyph instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphGlyph {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphGlyph($$parsedSource as Partial<GraphGlyph>);
    }
}

export class GraphLane {
    "Glyphs": GraphGlyph[];
    "ColorID": number;
    "CommitHash": string;

    /** Creates a new GraphLane instance. */
    constructor($$source: Partial<GraphLane> = {}) {
        if (!("Glyphs" in $$source)) {
            this["Glyphs"] = [];
        }
        if (!("ColorID" in $$source)) {
            this["ColorID"] = 0;
        }
        if (!("CommitHash" in $$source)) {
            this["CommitHash"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphLane instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphLane {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Glyphs" in $$parsedSource) {
            $$parsedSource["Glyphs"] = $$createField0_0($$parsedSource["Glyphs"]);
        }
        return new GraphLane($$parsedSource as Partial<GraphLane>);
    }
}

export class GraphLayout {
    "Rows": GraphLayoutRow[];
    "LaneCount": number;
    "CurrentBranch": string;

    /** Creates a new GraphLayout instance. */
    constructor($$source: Partial<GraphLayout> = {}) {
        if (!("Rows" in $$source)) {
            this["Rows"] = [];
        }
        if (!("LaneCount" in $$source)) {
            this["LaneCount"] = 0;
        }
        if (!("CurrentBranch" in $$source)) {
            this["CurrentBranch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphLayout instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphLayout {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Rows" in $$parsedSource) {
            $$parsedSource["Rows"] = $$createField0_0($$parsedSource["Rows"]);
        }
        return new GraphLayout($$parsedSource as Partial<GraphLayout>);
    }
}

export class GraphLayoutRow {
    "Commit": git$0.Commit | null;
    "Lanes": GraphLane[];

    /** Creates a new GraphLayoutRow instance. */
    constructor($$source: Partial<GraphLayoutRow> = {}) {
        if (!("Commit" in $$source)) {
            this["Commit"] = null;
        }
        if (!("Lanes" in $$source)) {
            this["Lanes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphLayoutRow instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphLayoutRow {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Commit" in $$parsedSource) {
            $$parsedSource["Commit"] = $$createField0_0($$parsedSource["Commit"]);
        }
        if ("Lanes" in $$parsedSource) {
            $$parsedSource["Lanes"] = $$createField1_0($$parsedSource["Lanes"]);
        }
        return new GraphLayoutRow($$parsedSource as Partial<GraphLayoutRow>);
    }
}

export class PRProviderStatus {
    "Remote": string;
    "URL": string;
    "Provider": string;
    "Repo": string;
    "Ready": boolean;

    /** Creates a new PRProviderStatus instance. */
    constructor($$source: Partial<PRProviderStatus> = {}) {
        if (!("Remote" in $$source)) {
            this["Remote"] = "";
        }
        if (!("URL" in $$source)) {
            this["URL"] = "";
        }
        if (!("Provider" in $$source)) {
            this["Provider"] = "";
        }
        if (!("Repo" in $$source)) {
            this["Repo"] = "";
        }
        if (!("Ready" in $$source)) {
            this["Ready"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PRProviderStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): PRProviderStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PRProviderStatus($$parsedSource as Partial<PRProviderStatus>);
    }
}

export class RemoteInfo {
    "Name": string;
    "URL": string;

    /** Creates a new RemoteInfo instance. */
    constructor($$source: Partial<RemoteInfo> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("URL" in $$source)) {
            this["URL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteInfo($$parsedSource as Partial<RemoteInfo>);
    }
}

export class RepoInfo {
    "Path": string;
    "Name": string;
    "Branch": string;
    "Head": string;
    "ShortHead": string;
    "DetachedHead": boolean;
    "HasUpstream": boolean;
    "HasUncommitted": boolean;
    "Ahead": number;
    "Behind": number;
    "Staged": git$0.ChangeStats;
    "Unstaged": git$0.ChangeStats;
    "StashCount": number;
    "Remotes": RemoteInfo[];

    /** Creates a new RepoInfo instance. */
    constructor($$source: Partial<RepoInfo> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Branch" in $$source)) {
            this["Branch"] = "";
        }
        if (!("Head" in $$source)) {
            this["Head"] = "";
        }
        if (!("ShortHead" in $$source)) {
            this["ShortHead"] = "";
        }
        if (!("DetachedHead" in $$source)) {
            this["DetachedHead"] = false;
        }
        if (!("HasUpstream" in $$source)) {
            this["HasUpstream"] = false;
        }
        if (!("HasUncommitted" in $$source)) {
            this["HasUncommitted"] = false;
        }
        if (!("Ahead" in $$source)) {
            this["Ahead"] = 0;
        }
        if (!("Behind" in $$source)) {
            this["Behind"] = 0;
        }
        if (!("Staged" in $$source)) {
            this["Staged"] = (new git$0.ChangeStats());
        }
        if (!("Unstaged" in $$source)) {
            this["Unstaged"] = (new git$0.ChangeStats());
        }
        if (!("StashCount" in $$source)) {
            this["StashCount"] = 0;
        }
        if (!("Remotes" in $$source)) {
            this["Remotes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RepoInfo {
        const $$createField10_0 = $$createType12;
        const $$createField11_0 = $$createType12;
        const $$createField13_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Staged" in $$parsedSource) {
            $$parsedSource["Staged"] = $$createField10_0($$parsedSource["Staged"]);
        }
        if ("Unstaged" in $$parsedSource) {
            $$parsedSource["Unstaged"] = $$createField11_0($$parsedSource["Unstaged"]);
        }
        if ("Remotes" in $$parsedSource) {
            $$parsedSource["Remotes"] = $$createField13_0($$parsedSource["Remotes"]);
        }
        return new RepoInfo($$parsedSource as Partial<RepoInfo>);
    }
}

// Private type creation functions
const $$createType0 = git$0.ConflictRegion.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = GraphGlyph.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = GraphLayoutRow.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = git$0.Commit.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = GraphLane.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = git$0.ChangeStats.createFrom;
const $$createType13 = RemoteInfo.createFrom;
const $$createType14 = $Create.Array($$createType13);
