// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "../../internal/git/models.js";

export class ConflictDocument {
    "MarkerSize": number;
    "RepoPath": string;
    "Path": string;
    "Token": string;
    "Base": ConflictVersion;
    "Current": ConflictVersion;
    "Incoming": ConflictVersion;
    "Result": string;
    "Exists": boolean;
    "Editable": boolean;
    "Reason": string;

    /** Creates a new ConflictDocument instance. */
    constructor($$source: Partial<ConflictDocument> = {}) {
        if (!("MarkerSize" in $$source)) {
            this["MarkerSize"] = 0;
        }
        if (!("RepoPath" in $$source)) {
            this["RepoPath"] = "";
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Token" in $$source)) {
            this["Token"] = "";
        }
        if (!("Base" in $$source)) {
            this["Base"] = (new ConflictVersion());
        }
        if (!("Current" in $$source)) {
            this["Current"] = (new ConflictVersion());
        }
        if (!("Incoming" in $$source)) {
            this["Incoming"] = (new ConflictVersion());
        }
        if (!("Result" in $$source)) {
            this["Result"] = "";
        }
        if (!("Exists" in $$source)) {
            this["Exists"] = false;
        }
        if (!("Editable" in $$source)) {
            this["Editable"] = false;
        }
        if (!("Reason" in $$source)) {
            this["Reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictDocument instance from a string or object.
     */
    static createFrom($$source: any = {}): ConflictDocument {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Base" in $$parsedSource) {
            $$parsedSource["Base"] = $$createField4_0($$parsedSource["Base"]);
        }
        if ("Current" in $$parsedSource) {
            $$parsedSource["Current"] = $$createField5_0($$parsedSource["Current"]);
        }
        if ("Incoming" in $$parsedSource) {
            $$parsedSource["Incoming"] = $$createField6_0($$parsedSource["Incoming"]);
        }
        return new ConflictDocument($$parsedSource as Partial<ConflictDocument>);
    }
}

export class ConflictEntry {
    "Path": string;
    "Kind": string;

    /** Creates a new ConflictEntry instance. */
    constructor($$source: Partial<ConflictEntry> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Kind" in $$source)) {
            this["Kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ConflictEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConflictEntry($$parsedSource as Partial<ConflictEntry>);
    }
}

export class ConflictFile {
    "Regions": (git$0.ConflictRegion | null)[];
    "Lines": string[];

    /** Creates a new ConflictFile instance. */
    constructor($$source: Partial<ConflictFile> = {}) {
        if (!("Regions" in $$source)) {
            this["Regions"] = [];
        }
        if (!("Lines" in $$source)) {
            this["Lines"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictFile instance from a string or object.
     */
    static createFrom($$source: any = {}): ConflictFile {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Regions" in $$parsedSource) {
            $$parsedSource["Regions"] = $$createField0_0($$parsedSource["Regions"]);
        }
        if ("Lines" in $$parsedSource) {
            $$parsedSource["Lines"] = $$createField1_0($$parsedSource["Lines"]);
        }
        return new ConflictFile($$parsedSource as Partial<ConflictFile>);
    }
}

export class ConflictStep {
    "Hash": string;
    "Subject": string;
    "State": string;

    /** Creates a new ConflictStep instance. */
    constructor($$source: Partial<ConflictStep> = {}) {
        if (!("Hash" in $$source)) {
            this["Hash"] = "";
        }
        if (!("Subject" in $$source)) {
            this["Subject"] = "";
        }
        if (!("State" in $$source)) {
            this["State"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictStep instance from a string or object.
     */
    static createFrom($$source: any = {}): ConflictStep {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConflictStep($$parsedSource as Partial<ConflictStep>);
    }
}

export class ConflictVersion {
    "Exists": boolean;
    "Content": string;
    "Mode": string;
    "Editable": boolean;

    /** Creates a new ConflictVersion instance. */
    constructor($$source: Partial<ConflictVersion> = {}) {
        if (!("Exists" in $$source)) {
            this["Exists"] = false;
        }
        if (!("Content" in $$source)) {
            this["Content"] = "";
        }
        if (!("Mode" in $$source)) {
            this["Mode"] = "";
        }
        if (!("Editable" in $$source)) {
            this["Editable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): ConflictVersion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConflictVersion($$parsedSource as Partial<ConflictVersion>);
    }
}

export class ConflictWorkspace {
    "RepoPath": string;
    "Token": string;
    "Kind": string;
    "CurrentLabel": string;
    "IncomingLabel": string;
    "Branch": string;
    "Onto": string;
    "Commit": string;
    "Subject": string;
    "Author": string;
    "OriginalHead": string;
    "Step": number;
    "Total": number;
    "Files": ConflictEntry[];
    "Staged": string[];
    "Steps": ConflictStep[];

    /** Creates a new ConflictWorkspace instance. */
    constructor($$source: Partial<ConflictWorkspace> = {}) {
        if (!("RepoPath" in $$source)) {
            this["RepoPath"] = "";
        }
        if (!("Token" in $$source)) {
            this["Token"] = "";
        }
        if (!("Kind" in $$source)) {
            this["Kind"] = "";
        }
        if (!("CurrentLabel" in $$source)) {
            this["CurrentLabel"] = "";
        }
        if (!("IncomingLabel" in $$source)) {
            this["IncomingLabel"] = "";
        }
        if (!("Branch" in $$source)) {
            this["Branch"] = "";
        }
        if (!("Onto" in $$source)) {
            this["Onto"] = "";
        }
        if (!("Commit" in $$source)) {
            this["Commit"] = "";
        }
        if (!("Subject" in $$source)) {
            this["Subject"] = "";
        }
        if (!("Author" in $$source)) {
            this["Author"] = "";
        }
        if (!("OriginalHead" in $$source)) {
            this["OriginalHead"] = "";
        }
        if (!("Step" in $$source)) {
            this["Step"] = 0;
        }
        if (!("Total" in $$source)) {
            this["Total"] = 0;
        }
        if (!("Files" in $$source)) {
            this["Files"] = [];
        }
        if (!("Staged" in $$source)) {
            this["Staged"] = [];
        }
        if (!("Steps" in $$source)) {
            this["Steps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictWorkspace instance from a string or object.
     */
    static createFrom($$source: any = {}): ConflictWorkspace {
        const $$createField13_0 = $$createType6;
        const $$createField14_0 = $$createType4;
        const $$createField15_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Files" in $$parsedSource) {
            $$parsedSource["Files"] = $$createField13_0($$parsedSource["Files"]);
        }
        if ("Staged" in $$parsedSource) {
            $$parsedSource["Staged"] = $$createField14_0($$parsedSource["Staged"]);
        }
        if ("Steps" in $$parsedSource) {
            $$parsedSource["Steps"] = $$createField15_0($$parsedSource["Steps"]);
        }
        return new ConflictWorkspace($$parsedSource as Partial<ConflictWorkspace>);
    }
}

/**
 * GitProfile describes identity settings, never credentials or private key material.
 */
export class GitProfile {
    "ID": string;
    "Label": string;
    "Name": string;
    "Email": string;
    "SigningKey": string;
    "SigningEnabled": string;
    "TagSigningEnabled": string;
    "SigningFormat": string;
    "Source": string;

    /** Creates a new GitProfile instance. */
    constructor($$source: Partial<GitProfile> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Email" in $$source)) {
            this["Email"] = "";
        }
        if (!("SigningKey" in $$source)) {
            this["SigningKey"] = "";
        }
        if (!("SigningEnabled" in $$source)) {
            this["SigningEnabled"] = "";
        }
        if (!("TagSigningEnabled" in $$source)) {
            this["TagSigningEnabled"] = "";
        }
        if (!("SigningFormat" in $$source)) {
            this["SigningFormat"] = "";
        }
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): GitProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitProfile($$parsedSource as Partial<GitProfile>);
    }
}

export class GitProfileCatalog {
    "Profiles": GitProfile[];
    "Warnings": string[];

    /** Creates a new GitProfileCatalog instance. */
    constructor($$source: Partial<GitProfileCatalog> = {}) {
        if (!("Profiles" in $$source)) {
            this["Profiles"] = [];
        }
        if (!("Warnings" in $$source)) {
            this["Warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitProfileCatalog instance from a string or object.
     */
    static createFrom($$source: any = {}): GitProfileCatalog {
        const $$createField0_0 = $$createType10;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Profiles" in $$parsedSource) {
            $$parsedSource["Profiles"] = $$createField0_0($$parsedSource["Profiles"]);
        }
        if ("Warnings" in $$parsedSource) {
            $$parsedSource["Warnings"] = $$createField1_0($$parsedSource["Warnings"]);
        }
        return new GitProfileCatalog($$parsedSource as Partial<GitProfileCatalog>);
    }
}

export class GraphGlyph {
    "Kind": string;
    "ColorID": number;
    "CommitHash": string;
    "ConnectTop": boolean;
    "ConnectBottom": boolean;

    /** Creates a new GraphGlyph instance. */
    constructor($$source: Partial<GraphGlyph> = {}) {
        if (!("Kind" in $$source)) {
            this["Kind"] = "";
        }
        if (!("ColorID" in $$source)) {
            this["ColorID"] = 0;
        }
        if (!("CommitHash" in $$source)) {
            this["CommitHash"] = "";
        }
        if (!("ConnectTop" in $$source)) {
            this["ConnectTop"] = false;
        }
        if (!("ConnectBottom" in $$source)) {
            this["ConnectBottom"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphGlyph instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphGlyph {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphGlyph($$parsedSource as Partial<GraphGlyph>);
    }
}

export class GraphLane {
    "Glyphs": GraphGlyph[];
    "ColorID": number;
    "CommitHash": string;

    /** Creates a new GraphLane instance. */
    constructor($$source: Partial<GraphLane> = {}) {
        if (!("Glyphs" in $$source)) {
            this["Glyphs"] = [];
        }
        if (!("ColorID" in $$source)) {
            this["ColorID"] = 0;
        }
        if (!("CommitHash" in $$source)) {
            this["CommitHash"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphLane instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphLane {
        const $$createField0_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Glyphs" in $$parsedSource) {
            $$parsedSource["Glyphs"] = $$createField0_0($$parsedSource["Glyphs"]);
        }
        return new GraphLane($$parsedSource as Partial<GraphLane>);
    }
}

export class GraphLayout {
    "Rows": GraphLayoutRow[];
    "LaneCount": number;
    "CurrentBranch": string;

    /** Creates a new GraphLayout instance. */
    constructor($$source: Partial<GraphLayout> = {}) {
        if (!("Rows" in $$source)) {
            this["Rows"] = [];
        }
        if (!("LaneCount" in $$source)) {
            this["LaneCount"] = 0;
        }
        if (!("CurrentBranch" in $$source)) {
            this["CurrentBranch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphLayout instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphLayout {
        const $$createField0_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Rows" in $$parsedSource) {
            $$parsedSource["Rows"] = $$createField0_0($$parsedSource["Rows"]);
        }
        return new GraphLayout($$parsedSource as Partial<GraphLayout>);
    }
}

export class GraphLayoutRow {
    "Commit": git$0.Commit | null;
    "Lanes": GraphLane[];

    /** Creates a new GraphLayoutRow instance. */
    constructor($$source: Partial<GraphLayoutRow> = {}) {
        if (!("Commit" in $$source)) {
            this["Commit"] = null;
        }
        if (!("Lanes" in $$source)) {
            this["Lanes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphLayoutRow instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphLayoutRow {
        const $$createField0_0 = $$createType16;
        const $$createField1_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Commit" in $$parsedSource) {
            $$parsedSource["Commit"] = $$createField0_0($$parsedSource["Commit"]);
        }
        if ("Lanes" in $$parsedSource) {
            $$parsedSource["Lanes"] = $$createField1_0($$parsedSource["Lanes"]);
        }
        return new GraphLayoutRow($$parsedSource as Partial<GraphLayoutRow>);
    }
}

export class PRProviderStatus {
    "Remote": string;
    "URL": string;
    "Provider": string;
    "Repo": string;
    "Ready": boolean;

    /** Creates a new PRProviderStatus instance. */
    constructor($$source: Partial<PRProviderStatus> = {}) {
        if (!("Remote" in $$source)) {
            this["Remote"] = "";
        }
        if (!("URL" in $$source)) {
            this["URL"] = "";
        }
        if (!("Provider" in $$source)) {
            this["Provider"] = "";
        }
        if (!("Repo" in $$source)) {
            this["Repo"] = "";
        }
        if (!("Ready" in $$source)) {
            this["Ready"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PRProviderStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): PRProviderStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PRProviderStatus($$parsedSource as Partial<PRProviderStatus>);
    }
}

export class RemoteInfo {
    "Name": string;
    "URL": string;

    /** Creates a new RemoteInfo instance. */
    constructor($$source: Partial<RemoteInfo> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("URL" in $$source)) {
            this["URL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteInfo($$parsedSource as Partial<RemoteInfo>);
    }
}

export class RepoInfo {
    "Path": string;
    "Name": string;
    "Branch": string;
    "Head": string;
    "ShortHead": string;
    "DetachedHead": boolean;
    "HasUpstream": boolean;
    "HasUncommitted": boolean;
    "Ahead": number;
    "Behind": number;
    "Staged": git$0.ChangeStats;
    "Unstaged": git$0.ChangeStats;
    "StashCount": number;
    "Remotes": RemoteInfo[];

    /** Creates a new RepoInfo instance. */
    constructor($$source: Partial<RepoInfo> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Branch" in $$source)) {
            this["Branch"] = "";
        }
        if (!("Head" in $$source)) {
            this["Head"] = "";
        }
        if (!("ShortHead" in $$source)) {
            this["ShortHead"] = "";
        }
        if (!("DetachedHead" in $$source)) {
            this["DetachedHead"] = false;
        }
        if (!("HasUpstream" in $$source)) {
            this["HasUpstream"] = false;
        }
        if (!("HasUncommitted" in $$source)) {
            this["HasUncommitted"] = false;
        }
        if (!("Ahead" in $$source)) {
            this["Ahead"] = 0;
        }
        if (!("Behind" in $$source)) {
            this["Behind"] = 0;
        }
        if (!("Staged" in $$source)) {
            this["Staged"] = (new git$0.ChangeStats());
        }
        if (!("Unstaged" in $$source)) {
            this["Unstaged"] = (new git$0.ChangeStats());
        }
        if (!("StashCount" in $$source)) {
            this["StashCount"] = 0;
        }
        if (!("Remotes" in $$source)) {
            this["Remotes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RepoInfo {
        const $$createField10_0 = $$createType19;
        const $$createField11_0 = $$createType19;
        const $$createField13_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Staged" in $$parsedSource) {
            $$parsedSource["Staged"] = $$createField10_0($$parsedSource["Staged"]);
        }
        if ("Unstaged" in $$parsedSource) {
            $$parsedSource["Unstaged"] = $$createField11_0($$parsedSource["Unstaged"]);
        }
        if ("Remotes" in $$parsedSource) {
            $$parsedSource["Remotes"] = $$createField13_0($$parsedSource["Remotes"]);
        }
        return new RepoInfo($$parsedSource as Partial<RepoInfo>);
    }
}

// Private type creation functions
const $$createType0 = ConflictVersion.createFrom;
const $$createType1 = git$0.ConflictRegion.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = ConflictEntry.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = ConflictStep.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = GitProfile.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = GraphGlyph.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = GraphLayoutRow.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = git$0.Commit.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = GraphLane.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = git$0.ChangeStats.createFrom;
const $$createType20 = RemoteInfo.createFrom;
const $$createType21 = $Create.Array($$createType20);
