// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PreferencesService persists application customization independently of Git state.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FormatRefLabels evaluates bounded, single-line Go text/templates in a batch.
 * Named templates are excluded to prevent recursion. Scalar data needs no range.
 */
export function FormatRefLabels(requests: $models.RefFormatRequest[]): $CancellablePromise<$models.RefFormatResult[]> {
    return $Call.ByID(3481062438, requests).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Load(): $CancellablePromise<$models.PreferenceSnapshot | null> {
    return $Call.ByID(998544923).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Save compares the exact file revision before atomically replacing the document.
 */
export function Save(expectedRevision: string, content: string): $CancellablePromise<$models.PreferenceSaveOutcome | null> {
    return $Call.ByID(3823687606, expectedRevision, content).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.RefFormatResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.PreferenceSnapshot.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.PreferenceSaveOutcome.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
