// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as remote$0 from "../../internal/remote/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddComment(remoteName: string, id: number, body: string): $CancellablePromise<remote$0.Comment | null> {
    return $Call.ByID(1864685303, remoteName, id, body).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ClosePR(remoteName: string, id: number): $CancellablePromise<void> {
    return $Call.ByID(4289372759, remoteName, id);
}

export function GetChecks(remoteName: string, id: number): $CancellablePromise<remote$0.Check[]> {
    return $Call.ByID(4179694200, remoteName, id).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetPR(remoteName: string, id: number): $CancellablePromise<remote$0.PullRequest | null> {
    return $Call.ByID(1561911499, remoteName, id).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetPRDiff(remoteName: string, id: number): $CancellablePromise<string> {
    return $Call.ByID(1171163448, remoteName, id);
}

export function GetPRFiles(remoteName: string, id: number): $CancellablePromise<remote$0.ChangedFile[]> {
    return $Call.ByID(3392013378, remoteName, id).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListComments(remoteName: string, id: number): $CancellablePromise<remote$0.Comment[]> {
    return $Call.ByID(600683321, remoteName, id).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListPRs(remoteName: string, opts: remote$0.ListPRsOpts): $CancellablePromise<remote$0.PullRequest[]> {
    return $Call.ByID(639477490, remoteName, opts).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ListReviews(remoteName: string, id: number): $CancellablePromise<remote$0.Review[]> {
    return $Call.ByID(4118394196, remoteName, id).then(($result: any) => {
        return $$createType11($result);
    });
}

export function MergePR(remoteName: string, id: number, opts: remote$0.MergeOpts): $CancellablePromise<void> {
    return $Call.ByID(204746599, remoteName, id, opts);
}

export function ProviderStatus(remoteName: string): $CancellablePromise<$models.PRProviderStatus | null> {
    return $Call.ByID(3608740416, remoteName).then(($result: any) => {
        return $$createType13($result);
    });
}

export function SubmitReview(remoteName: string, id: number, input: remote$0.SubmitReviewInput): $CancellablePromise<void> {
    return $Call.ByID(1180859759, remoteName, id, input);
}

// Private type creation functions
const $$createType0 = remote$0.Comment.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = remote$0.Check.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = remote$0.PullRequest.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = remote$0.ChangedFile.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($$createType0);
const $$createType9 = $Create.Array($$createType4);
const $$createType10 = remote$0.Review.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.PRProviderStatus.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
