// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "../../internal/git/models.js";

export function Checkout(ref: string): $CancellablePromise<void> {
    return $Call.ByID(4159343680, ref);
}

export function CheckoutBranch(branch: string, create: boolean): $CancellablePromise<void> {
    return $Call.ByID(4197903248, branch, create);
}

export function CherryPick(hash: string): $CancellablePromise<void> {
    return $Call.ByID(377947564, hash);
}

export function CreateBranch(name: string): $CancellablePromise<void> {
    return $Call.ByID(3819752336, name);
}

export function CreateBranchAt(name: string, ref: string): $CancellablePromise<void> {
    return $Call.ByID(3433294165, name, ref);
}

export function CreateTag(name: string, ref: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(1988845632, name, ref, message);
}

export function DeleteBranch(name: string, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(737985711, name, force);
}

export function DeleteRemoteBranch(remote: string, branch: string): $CancellablePromise<void> {
    return $Call.ByID(3988070317, remote, branch);
}

export function DeleteTag(name: string): $CancellablePromise<void> {
    return $Call.ByID(3749695349, name);
}

export function ListBranches(): $CancellablePromise<git$0.Branch[]> {
    return $Call.ByID(1923967296).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListLocalBranches(): $CancellablePromise<git$0.Branch[]> {
    return $Call.ByID(3104167103).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListRemoteBranches(): $CancellablePromise<git$0.Branch[]> {
    return $Call.ByID(2266018530).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListTags(): $CancellablePromise<git$0.Tag[]> {
    return $Call.ByID(2626891877).then(($result: any) => {
        return $$createType3($result);
    });
}

export function MergeBranch(branch: string): $CancellablePromise<void> {
    return $Call.ByID(635670280, branch);
}

export function PushTag(remote: string, tag: string): $CancellablePromise<void> {
    return $Call.ByID(2511460176, remote, tag);
}

export function RebaseBranch(onto: string): $CancellablePromise<void> {
    return $Call.ByID(3639865752, onto);
}

export function RenameBranch(oldName: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(1580592934, oldName, newName);
}

export function ResetHard(ref: string): $CancellablePromise<void> {
    return $Call.ByID(2260796214, ref);
}

export function ResetSoft(ref: string): $CancellablePromise<void> {
    return $Call.ByID(2689658927, ref);
}

export function Revert(hash: string): $CancellablePromise<void> {
    return $Call.ByID(1878114962, hash);
}

export function SetUpstream(local: string, remote: string): $CancellablePromise<void> {
    return $Call.ByID(3075745849, local, remote);
}

// Private type creation functions
const $$createType0 = git$0.Branch.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = git$0.Tag.createFrom;
const $$createType3 = $Create.Array($$createType2);
