// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Fetch(remote: string): $CancellablePromise<void> {
    return $Call.ByID(1755606605, remote);
}

export function FetchAll(): $CancellablePromise<void> {
    return $Call.ByID(453194908);
}

export function HasUpstream(): $CancellablePromise<boolean> {
    return $Call.ByID(2030610020);
}

export function Pull(): $CancellablePromise<void> {
    return $Call.ByID(872710636);
}

export function Push(): $CancellablePromise<void> {
    return $Call.ByID(970566231);
}

export function PushSetUpstream(remote: string, branch: string): $CancellablePromise<void> {
    return $Call.ByID(4087632664, remote, branch);
}
