// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../../internal/config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteRepo(name: string): $CancellablePromise<void> {
    return $Call.ByID(3755562590, name);
}

export function Info(): $CancellablePromise<$models.RepoInfo | null> {
    return $Call.ByID(351162597).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListRemotes(): $CancellablePromise<string[]> {
    return $Call.ByID(366738476).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListSavedRepos(): $CancellablePromise<config$0.Repo[]> {
    return $Call.ByID(2145046829).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Open(path: string): $CancellablePromise<$models.RepoInfo | null> {
    return $Call.ByID(4099943593, path).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RemoteURL(name: string): $CancellablePromise<string> {
    return $Call.ByID(2402022628, name);
}

export function SaveRepo(oldName: string, repo: config$0.Repo): $CancellablePromise<void> {
    return $Call.ByID(1702464948, oldName, repo);
}

export function SetPath(path: string): $CancellablePromise<$models.RepoInfo | null> {
    return $Call.ByID(2449170404, path).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.RepoInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = config$0.Repo.createFrom;
const $$createType4 = $Create.Array($$createType3);
