// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Compare(base: string, head: string): $CancellablePromise<$models.ReviewSnapshot | null> {
    return $Call.ByID(1132172728, base, head).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Generate(id: string, options: $models.ReviewOptions): $CancellablePromise<$models.ReviewWalkthrough | null> {
    return $Call.ByID(1938168486, id, options).then(($result: any) => {
        return $$createType3($result);
    });
}

export function IsOutdated(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(2350531097, id);
}

// Private type creation functions
const $$createType0 = $models.ReviewSnapshot.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ReviewWalkthrough.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
