// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Capabilities(): $CancellablePromise<$models.SearchCapabilities> {
    return $Call.ByID(4281093699).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Content is a bounded literal search. Ripgrep's ignore rules remain enabled,
 * hidden files are included, and symlinks are not followed.
 */
export function Content(query: string, limit: number): $CancellablePromise<$models.ContentSearchResult | null> {
    return $Call.ByID(390082358, query, limit).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Files scans an immutable, normalized index and retains only the best K
 * results. No per-keystroke subprocess or full file-list bridge transfer.
 */
export function Files(query: string, limit: number, recent: string[]): $CancellablePromise<$models.FileSearchResult | null> {
    return $Call.ByID(2340162124, query, limit, recent).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SearchCapabilities.createFrom;
const $$createType1 = $models.ContentSearchResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.FileSearchResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
