// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "../../internal/git/models.js";

export function ListStashes(): $CancellablePromise<git$0.Stash[]> {
    return $Call.ByID(898146453).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StashApplyIndex(index: number): $CancellablePromise<void> {
    return $Call.ByID(2706241645, index);
}

export function StashBranch(branchName: string, index: number): $CancellablePromise<void> {
    return $Call.ByID(2084898505, branchName, index);
}

export function StashClear(): $CancellablePromise<void> {
    return $Call.ByID(2198339318);
}

export function StashDropIndex(index: number): $CancellablePromise<void> {
    return $Call.ByID(3089403396, index);
}

export function StashPopIndex(index: number): $CancellablePromise<void> {
    return $Call.ByID(3258477560, index);
}

export function StashPush(message: string, includeUntracked: boolean): $CancellablePromise<void> {
    return $Call.ByID(3732310833, message, includeUntracked);
}

export function StashShow(index: number): $CancellablePromise<string> {
    return $Call.ByID(59265256, index);
}

export function StashStaged(message: string): $CancellablePromise<void> {
    return $Call.ByID(3772701127, message);
}

// Private type creation functions
const $$createType0 = git$0.Stash.createFrom;
const $$createType1 = $Create.Array($$createType0);
