// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "../../internal/git/models.js";

export function Commit(message: string): $CancellablePromise<void> {
    return $Call.ByID(2799605265, message);
}

export function CommitAmend(message: string): $CancellablePromise<void> {
    return $Call.ByID(3632320564, message);
}

export function DiscardFileChanges(path: string): $CancellablePromise<void> {
    return $Call.ByID(44116913, path);
}

export function StageAll(): $CancellablePromise<void> {
    return $Call.ByID(3489174377);
}

export function StageFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(84202900, path);
}

export function StagedFiles(): $CancellablePromise<git$0.StatusEntry[]> {
    return $Call.ByID(4119002197).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Status(): $CancellablePromise<git$0.StatusEntry[]> {
    return $Call.ByID(1718111886).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UnstageAll(): $CancellablePromise<void> {
    return $Call.ByID(685188550);
}

export function UnstageFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(1344493549, path);
}

export function UnstagedFiles(): $CancellablePromise<git$0.StatusEntry[]> {
    return $Call.ByID(651784768).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UntrackedFiles(): $CancellablePromise<git$0.StatusEntry[]> {
    return $Call.ByID(532524702).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = git$0.StatusEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
