// Generated by scripts/generate-themes.mjs from dado theme defs. DO NOT EDIT.

export const THEMES = [
  { id: 'atterpac', label: 'Atterpac', light: false },
  { id: 'ayu-dark', label: 'Ayu Dark', light: false },
  { id: 'ayu-light', label: 'Ayu Light', light: true },
  { id: 'catppuccin-frappe', label: 'Catppuccin Frappe', light: false },
  { id: 'catppuccin-latte', label: 'Catppuccin Latte', light: true },
  { id: 'catppuccin-macchiato', label: 'Catppuccin Macchiato', light: false },
  { id: 'catppuccin-mocha', label: 'Catppuccin Mocha', light: false },
  { id: 'dracula', label: 'Dracula', light: false },
  { id: 'dracula-light', label: 'Dracula Light', light: true },
  { id: 'everforest-dark', label: 'Everforest Dark', light: false },
  { id: 'everforest-light', label: 'Everforest Light', light: true },
  { id: 'flexoki-dark', label: 'Flexoki Dark', light: false },
  { id: 'github-dark', label: 'GitHub Dark', light: false },
  { id: 'github-light', label: 'GitHub Light', light: true },
  { id: 'gruvbox-dark', label: 'Gruvbox Dark', light: false },
  { id: 'gruvbox-light', label: 'Gruvbox Light', light: true },
  { id: 'kanagawa', label: 'Kanagawa', light: false },
  { id: 'monokai', label: 'Monokai', light: false },
  { id: 'nightfox', label: 'Nightfox', light: false },
  { id: 'nord', label: 'Nord', light: false },
  { id: 'onedark', label: 'One Dark', light: false },
  { id: 'onelight', label: 'One Light', light: true },
  { id: 'oxocarbon', label: 'Oxocarbon', light: false },
  { id: 'palenight', label: 'Palenight', light: false },
  { id: 'rosepine', label: 'Rosé Pine', light: false },
  { id: 'rosepine-dawn', label: 'Rosé Pine Dawn', light: true },
  { id: 'rosepine-moon', label: 'Rosé Pine Moon', light: false },
  { id: 'solarized-dark', label: 'Solarized Dark', light: false },
  { id: 'solarized-light', label: 'Solarized Light', light: true },
  { id: 'tokyonight-day', label: 'Tokyo Night Day', light: true },
  { id: 'tokyonight-moon', label: 'Tokyo Night Moon', light: false },
  { id: 'tokyonight-night', label: 'Tokyo Night', light: false },
  { id: 'tokyonight-storm', label: 'Tokyo Night Storm', light: false },
] as const

export type ThemeId = (typeof THEMES)[number]['id']

export const DEFAULT_THEME: ThemeId = 'tokyonight-night'

export function isThemeId(value: unknown): value is ThemeId {
  return THEMES.some((theme) => theme.id === value)
}

export function isLightTheme(id: string): boolean {
  return THEMES.find((theme) => theme.id === id)?.light ?? false
}
